"""Synthetic C06 Qt renders; generated bytes only, no provider or personal state."""
from __future__ import annotations

import argparse
import hashlib
import io
import json
import os
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")
os.environ.setdefault("QT_SCALE_FACTOR", "2")

from PySide6.QtCore import QObject, Signal


class QueuedTasks(QObject):
    task_finished = Signal(str)
    task_cancelled = Signal(str, str)

    def __init__(self):
        super().__init__()
        self.pending, self.cancelled, self.serial = [], set(), 0

    def submit(self, label, operation, *, on_success=None, on_failure=None):
        self.serial += 1
        identifier = str(self.serial)
        self.pending.append((identifier, label, operation, on_success, on_failure))
        return identifier

    def submit_progress(self, label, operation, *, on_success=None, on_failure=None, on_progress=None):
        return self.submit(label, lambda: operation(on_progress or (lambda _: None), lambda: False),
                           on_success=on_success, on_failure=on_failure)

    def cancel(self, identifier):
        self.cancelled.add(identifier)

    def flush(self):
        count = 0
        while self.pending:
            identifier, label, operation, success, failure = self.pending.pop(0)
            if identifier in self.cancelled:
                self.task_cancelled.emit(identifier, label)
            else:
                try:
                    value = operation()
                except Exception as exc:
                    if failure:
                        failure(str(exc))
                    else:
                        raise
                else:
                    if success:
                        success(value)
            self.task_finished.emit(identifier)
            count += 1
            assert count < 100


class PreviewFixture:
    def __init__(self, mode):
        from docx import Document
        from integrations.deeptutor_shchem_v1.desktop_preparation_sources import PreparationSourcesService
        self.reader = PreparationSourcesService(ROOT)
        self.calls = []
        self.bytes = {}
        rows, identities = [], {}
        kinds = ["existing", "new_version", "new"] if mode in {"mixed", "context"} else ["new_version" if mode == "version" else "existing"]
        for index, kind in enumerate(kinds, 1):
            doc = Document()
            doc.add_heading("合成讲义 · 仅用于界面验收", 1)
            doc.add_paragraph("【例1】比较两份记录的实验条件，并指出需要保持一致的量。")
            doc.add_paragraph(f"合成资料 {index}：表格、图形和条件应对照原文核对。")
            doc.add_paragraph("【答案】此处为合成参考文字，不代表真实试题或教师审核。")
            output = io.BytesIO(); doc.save(output)
            raw = output.getvalue()
            identifier = f"synthetic-{index}"
            name = "更名后的合成电解质讲义（保留原教师标签与题目范围）.docx" if kind == "existing" else "合成化学平衡讲义.docx" if kind == "new_version" else "另一份新讲义.docx"
            row = {"source_id": identifier, "role": "answer" if mode == "context" and index == 2 else "handout",
                   "order_index": index, "kind": "docx", "source_name": name,
                   "source_sha256": hashlib.sha256(raw).hexdigest()}
            rows.append(row); self.bytes[identifier] = raw
            target = {"batch_id": "SYNTHETIC-OLD", "archive_source_id": "SYNTHETIC-SOURCE",
                      "source_sha256": row["source_sha256"], "source_name": "原来的合成电解质讲义.docx",
                      "role": "handout", "visual_status": "not_required"}
            identities[identifier] = {"status": kind, "existing": target if kind == "existing" else None,
                                     "same_name_versions": [target] if kind == "new_version" else []}
        self.preview = {"preview_id": "SYNTHETIC-PREVIEW", "revision": "SYNTHETIC-REVISION",
                        "sources": rows, "warnings": [],
                        "identities": {"schema": "word-import-identity.v1", "revision": "SYNTHETIC-IDENTITY", "items": identities}}

    def preview_import_source(self, preview_id, revision, source_id):
        from integrations.deeptutor_shchem_v1.desktop_word_question_index import index_word_questions
        self.calls.append((preview_id, revision, source_id))
        row = next(row for row in self.preview["sources"] if row["source_id"] == source_id)
        preview = self.reader.word_preview_bytes(self.bytes[source_id], row["source_name"])
        return {**row, "preview": preview, "questions": index_word_questions(preview), "warnings": []}


class ResultFixture:
    def __init__(self, mode):
        from dataclasses import replace
        from integrations.deeptutor_shchem_v1.desktop_facade import DesktopVisualImportReceipt, DesktopVisualImportSourceSummary
        self.old = DesktopVisualImportReceipt("SYNTHETIC-OLD", "合成讲义", "candidate_ready_for_review", "not_required",
            1, 1, 0, (DesktopVisualImportSourceSummary("handout", 1, "合成化学平衡讲义.docx", "native_text_complete"),),
            "合成已有资料", native_completed_count=1)
        target = {"batch_id": self.old.batch_id, "archive_source_id": "SYNTHETIC-SOURCE", "source_sha256": "a" * 64,
                  "source_name": self.old.sources[0].filename, "role": "handout", "visual_status": "not_required"}
        if mode == "continued":
            self.receipt = replace(self.old, import_review={"new_count": 0, "reused": [target], "reused_receipts": (self.old,), "repeated_count": 0, "version_count": 0})
            self.history = (self.old,)
        else:
            self.receipt = replace(self.old, batch_id="SYNTHETIC-NEW", import_review={"new_count": 1, "reused": [], "reused_receipts": (), "repeated_count": 0, "version_count": 1})
            self.history = (self.old, self.receipt)

    def list_import_batches(self): return self.history
    def list_imported_word_batches(self): return self.history
    def list_provider_profiles(self): return ()
    def import_batch_details(self, batch_id):
        return next(value for value in self.history if value.batch_id == batch_id)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--empty-source-only", action="store_true", help="只复核限定原来源的空态，不重拍已验收导入流程。")
    args = parser.parse_args()
    output = args.output.resolve()
    output.mkdir(parents=True, exist_ok=False)
    from PySide6.QtCore import QCoreApplication, QEvent
    from integrations.deeptutor_shchem_v1.desktop_workbench.app import create_application
    from integrations.deeptutor_shchem_v1.desktop_workbench.import_preview_dialog import ImportPreviewDialog
    app = create_application(["word-import-identity-qa"])
    records = []
    for mode in (() if args.empty_source_only else ("existing", "version", "mixed", "context", "processing")):
        for width, height in ((360, 520), (420, 680), (900, 760)):
            facade, tasks = PreviewFixture(mode), QueuedTasks()
            dialog = ImportPreviewDialog(facade, tasks, facade.preview)
            dialog.resize(width, height); dialog.show()
            if mode != "processing":
                tasks.flush()
            dialog.select_all.click()
            for _ in range(40):
                app.processEvents()
            assert (dialog.width(), dialog.height()) == (width, height)
            assert dialog.confirm_button.isEnabled() == (mode not in {"context", "processing"})
            for position in (("top", "bottom") if width == 360 else ("whole",)):
                dialog.scroll.verticalScrollBar().setValue(dialog.scroll.verticalScrollBar().maximum() if position == "bottom" else 0)
                for _ in range(10): app.processEvents()
                for button in (dialog.confirm_button, dialog.cancel_button):
                    assert dialog.rect().contains(button.mapTo(dialog, button.rect().bottomRight()))
                assert dialog.scroll.horizontalScrollBar().maximum() == 0
                path = output / f"identity-{mode}-{width}x{height}-{position}.png"
                assert dialog.grab().save(str(path))
                records.append({"path": str(path), "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
                    "mode": mode, "width": width, "height": height, "device_pixel_ratio": dialog.devicePixelRatioF(),
                    "confirm_enabled": dialog.confirm_button.isEnabled(), "summary": dialog.action_summary.text()})
            dialog.reject(); tasks.flush(); dialog.deleteLater()
            QCoreApplication.sendPostedEvents(None, QEvent.Type.DeferredDelete)
            app.processEvents()
    from integrations.deeptutor_shchem_v1.desktop_workbench.dialogs import ImportDialog
    for mode in (() if args.empty_source_only else ("continued", "version_saved")):
        for width, height in ((360, 520), (420, 680)):
            facade, tasks = ResultFixture(mode), QueuedTasks()
            dialog = ImportDialog(facade, tasks)
            dialog.resize(width, height); dialog.show()
            dialog._visual_batch_saved(facade.receipt)
            for _ in range(40): app.processEvents()
            dialog.scroll.ensureWidgetVisible(dialog.word_continuation if mode == "continued" else dialog.word_history_card)
            for _ in range(20): app.processEvents()
            assert (dialog.width(), dialog.height()) == (width, height)
            if mode == "continued":
                for button in (dialog.continue_questions_button, dialog.continue_original_button, dialog.continue_progress_button):
                    dialog.scroll.ensureWidgetVisible(button)
                    for _ in range(10): app.processEvents()
                    assert dialog.scroll.viewport().rect().contains(button.mapTo(dialog.scroll.viewport(), button.rect().center()))
            path = output / f"identity-{mode}-{width}x{height}.png"
            assert dialog.grab().save(str(path))
            records.append({"path": str(path), "sha256": hashlib.sha256(path.read_bytes()).hexdigest(), "mode": mode,
                "width": width, "height": height, "device_pixel_ratio": dialog.devicePixelRatioF(), "summary": dialog.import_identity_summary.text()})
            dialog.close(); dialog.deleteLater()
            QCoreApplication.sendPostedEvents(None, QEvent.Type.DeferredDelete); app.processEvents()
    # The existing question reader retains its own 400x600 minimum; this
    # capture verifies the new empty-source boundary, not a reader redesign.
    from integrations.deeptutor_shchem_v1.desktop_workbench.word_question_dialog import WordQuestionDialog
    class EmptySourceFixture:
        def word_question_catalog(self):
            return {"revision": "synthetic", "sources": [], "items": [], "warnings": []}
        def word_question_saved_selection(self): return []
    tasks = QueuedTasks()
    dialog = WordQuestionDialog(EmptySourceFixture(), tasks,
        initial_source_id="a" * 64, required_source_id="a" * 64)
    dialog.resize(900, 760); dialog.show(); tasks.flush()
    for _ in range(40): app.processEvents()
    assert dialog.question_list.count() == 0 and "未显示其他来源" in dialog.status.text()
    assert dialog.source_combo.count() == 1 and not dialog.source_combo.isEnabled()
    assert not dialog.multi_filter_panel.buttons["source"].isEnabled()
    assert dialog._panel_layouts[0].itemAt(0).widget().text() == "原来源当前没有可用题目，请返回查看原文或原批次进度。"
    path = output / "identity-required-source-empty-900x760.png"
    assert dialog.grab().save(str(path))
    records.append({"path": str(path), "sha256": hashlib.sha256(path.read_bytes()).hexdigest(), "mode": "required_source_empty",
        "width": dialog.width(), "height": dialog.height(), "device_pixel_ratio": dialog.devicePixelRatioF(), "summary": dialog.status.text()})
    dialog.close(); dialog.deleteLater(); QCoreApplication.sendPostedEvents(None, QEvent.Type.DeferredDelete); app.processEvents()
    (output / "manifest.json").write_text(json.dumps({"scope": "generated DOCX bytes + controlled Qt service only",
        "personal_state_accessed": False, "provider_calls": 0, "scale_factor": os.environ["QT_SCALE_FACTOR"],
        "captures": records}, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps({"output": str(output), "captures": len(records)}, ensure_ascii=False))


if __name__ == "__main__":
    main()
